
modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
modId="storagedelight"
version="24.11.26-1.19.2-forge"
displayName="Storage Delight"
logoFile="logo.png"
authors="Axperty"
description='''A mod that adds more storage options to the game.'''

[[dependencies.storagedelight]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.storagedelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
